name: Déploiement sur Compute Engine

on:
  push:
    branches:
      - main # ou toute autre branche que tu veux surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configure Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Exécute le script sur l'instance Compute Engine
        run: |
          gcloud compute ssh instance-20240611-180413 \
            --zone=us-central1-c \
            --command="cd document-extraction-gemini && sudo sh deploy.sh"
