name: Déploiement sur Compute Engine

on:
  push:
    branches:
      - main # ou toute autre branche que tu veux surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Authentification à Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configuration de gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Exécute le script sur l'instance Compute Engine
        run: |
          gcloud compute ssh instance-20240611-180413 \
            --zone=us-central1-c \
            --command="cd document-extraction-gemini && sudo sh deploy.sh"
